"""Original v0901 defaults, limited to its three supported datasets."""
DATASET_DEFAULTS = {
    "Grid": {
        "encoder_blocks": 5,
        "graphEmDim": 64,
        "cond_dim": 64,
        "struct_cond_dim": 32,
        "decoder_node_dim": 192,
        "dit_hidden_dim": 384,
        "dit_num_heads": 8,
        "dit_num_layers": 6,
        "lap_pe_dim": 16,
        "flow_steps": 200,
        "flow_base_std": 1.0,
        "decode_mode": "topE",
        "connectivity_repair": True,
        "degree_reg_weight": 0.20,   # heavy on degree (regular degree-4)
        "degree_aux_weight": 0.10,
        "candidate_multiplier": 4,
        "val_eval_interval": 100,
        "flow_val_eval_interval": 200,
        "directed": False,
        "bfsOrdering": True,
    },
    "planar": {
        "encoder_blocks": 5,
        "graphEmDim": 64,
        "cond_dim": 64,
        "struct_cond_dim": 32,
        "decoder_node_dim": 192,
        "dit_hidden_dim": 384,
        "dit_num_heads": 8,
        "dit_num_layers": 6,
        "lap_pe_dim": 16,
        "flow_steps": 200,
        "flow_base_std": 1.0,
        "decode_mode": "topE",
        "structure_constraint": "planar",
        "benchmark_ordering": "structural_bfs",
        "degree_profile_blend": 0.50,
        "constraint_noise_scale": 0.05,
        "degree_hist_budget_calibration": True,
        "degree_hist_temperature": 0.50,
        "unique_candidate_select": True,
        "connectivity_repair": True,
        "profile_select": True,
        "degree_reg_weight": 0.20,
        "degree_aux_weight": 0.10,
        "candidate_multiplier": 8,
        "val_eval_interval": 100,
        "flow_val_eval_interval": 200,
        "directed": False,
        "bfsOrdering": False,
    },
    "tree": {
        "encoder_blocks": 5,
        "graphEmDim": 64,
        "cond_dim": 64,
        "struct_cond_dim": 32,
        "decoder_node_dim": 192,
        "dit_hidden_dim": 384,
        "dit_num_heads": 8,
        "dit_num_layers": 6,
        "lap_pe_dim": 16,
        "flow_steps": 200,
        "flow_base_std": 1.0,
        "decode_mode": "topE",
        "structure_constraint": "tree",
        "benchmark_ordering": "structural_bfs",
        "degree_profile_blend": 0.75,
        "constraint_noise_scale": 0.05,
        "degree_hist_budget_calibration": True,
        "degree_hist_temperature": 0.50,
        "unique_candidate_select": True,
        "connectivity_repair": True,
        "profile_select": True,
        "degree_reg_weight": 0.20,
        "degree_aux_weight": 0.10,
        "candidate_multiplier": 8,
        "val_eval_interval": 100,
        "flow_val_eval_interval": 200,
        "directed": False,
        "bfsOrdering": False,
    }
}
DATASET_DEFAULTS["grid"] = DATASET_DEFAULTS["Grid"]
